"""Generate ontoloom/ontology/patterns/_generated.py from the axiom hierarchy.

Walks model_fields of every expression and axiom class, reads type annotations
via get_type_hints (preserves alias identity), and emits the parallel pattern
hierarchy by substituting IRI→Slot, ClassExpression→ExprSlot, DataRange→DataRange|Slot,
and appending |Contains to Unordered tuple fields.

Run: uv run python -m ontoloom.codegen.gen_patterns
"""

from __future__ import annotations

import sys
import types
import typing
from pathlib import Path
from typing import Annotated, get_args, get_origin

from ontoloom.ontology.models.axioms import Axiom
from ontoloom.ontology.models.base import TYPE_FIELD
from ontoloom.ontology.models.expressions import ClassExpression
from ontoloom.ontology.models.literals import IRI, DataRange
from ontoloom.ontology.models.markers import is_unordered

_HEADER = "# Generated by ontoloom.codegen.gen_patterns. DO NOT EDIT.\n"
_SKIP_FIELDS = frozenset((TYPE_FIELD, "annotations"))
_TARGET = Path(__file__).parent.parent / "ontology" / "patterns" / "_generated.py"

_EXPR_CLASSES: tuple[type, ...] = get_args(get_args(ClassExpression)[0])
_AXIOM_CLASSES: tuple[type, ...] = get_args(get_args(Axiom)[0])
_PATTERN_CLASSES: frozenset[type] = frozenset(_EXPR_CLASSES) | frozenset(_AXIOM_CLASSES)

# The raw ClassExpression union (without the Annotated wrapper).
# Annotated[ClassExpression, marker] flattens nested Annotated to
# Annotated[_EXPR_UNION, Field(...), marker], so we detect ExprSlot fields
# by checking whether the first Annotated arg IS this union, not the alias.
_EXPR_UNION = get_args(ClassExpression)[0]

_IMPORTS = """\
from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ontoloom.ontology.models.literals import (
    DataRange,
    EntityType,
    FrozenModel,
    IRI,
    LangLiteral,
    TypedLiteral,
)
from ontoloom.ontology.patterns.slot import Slot"""


def generate() -> str:
    lines: list[str] = [_HEADER, _IMPORTS, ""]
    lines += [
        "class Contains(FrozenModel):",
        '    """Partial-set match: actual list must contain at least these items."""',
        "    contains: tuple[ExprSlot, ...]",
        "",
    ]

    needs_rebuild: list[str] = ["Contains"]

    for cls in _EXPR_CLASSES:
        class_lines, rebuild = _emit_class(cls)
        lines.extend(class_lines)
        lines.append("")
        if rebuild:
            needs_rebuild.append(cls.__name__ + "Pattern")

    lines.append(f"ExprSlot = Slot | {' | '.join(c.__name__ + 'Pattern' for c in _EXPR_CLASSES)}")
    lines.append("")

    for cls in _AXIOM_CLASSES:
        class_lines, rebuild = _emit_class(cls)
        lines.extend(class_lines)
        lines.append("")
        if rebuild:
            needs_rebuild.append(cls.__name__ + "Pattern")

    expr_names = " | ".join(c.__name__ + "Pattern" for c in _EXPR_CLASSES)
    axiom_names = " | ".join(c.__name__ + "Pattern" for c in _AXIOM_CLASSES)
    lines += [
        f"ExpressionPattern = {expr_names}",
        f"AxiomPattern = {axiom_names}",
        'Pattern = Annotated[ExpressionPattern | AxiomPattern, Field(discriminator="type")]',
        "",
    ]
    lines.extend(f"{name}.model_rebuild()" for name in needs_rebuild)

    return "\n".join(lines) + "\n"


def _emit_class(cls: type) -> tuple[list[str], bool]:
    pattern_name = cls.__name__ + "Pattern"
    lines: list[str] = [f"class {pattern_name}(FrozenModel):"]
    lines.append(f'    type: Literal["{pattern_name}"] = "{pattern_name}"')

    needs_rebuild = False
    hints = typing.get_type_hints(cls, include_extras=True)
    for field_name, info in cls.model_fields.items():
        if field_name in _SKIP_FIELDS:
            continue
        field_type = _to_pattern_type(hints[field_name], is_unordered(info))
        lines.append(f"    {field_name}: {field_type}")
        if "ExprSlot" in field_type or "Contains" in field_type:
            needs_rebuild = True

    return lines, needs_rebuild


def _to_pattern_type(t: object, unordered: bool = False) -> str:
    if get_origin(t) is Annotated:
        args = get_args(t)
        # Annotated[ClassExpression, marker] flattens to Annotated[_EXPR_UNION, Field, marker]
        # so we must detect ExprSlot here before stripping, not after.
        if args[0] is _EXPR_UNION:
            return "ExprSlot"
        return _to_pattern_type(args[0], unordered)

    if t is IRI:
        return "Slot"
    if t is _EXPR_UNION:
        return "ExprSlot"
    if t is DataRange:
        return "DataRange | Slot"

    origin = get_origin(t)

    if origin is tuple:
        args = get_args(t)
        inner = _to_pattern_type(args[0])
        base = f"tuple[{inner}, ...]"
        return f"{base} | Contains" if unordered else base

    if origin is types.UnionType or origin is typing.Union:
        parts = [_union_member(arg) for arg in get_args(t)]
        if "Slot" not in parts:
            parts.append("Slot")
        return " | ".join(parts)

    if isinstance(t, type) and t in _PATTERN_CLASSES:
        return t.__name__ + "Pattern"

    name = getattr(t, "__name__", None)
    return f"{name} | Slot" if name else repr(t)


def _union_member(t: object) -> str:
    """Render a type that appears inside a union. IRI is kept as IRI (not collapsed to Slot)."""
    if t is IRI:
        return "IRI"
    if t is _EXPR_UNION:
        return "ExprSlot"
    if t is DataRange:
        return "DataRange"
    if isinstance(t, type) and t in _PATTERN_CLASSES:
        return t.__name__ + "Pattern"
    if get_origin(t) is Annotated:
        args = get_args(t)
        if args[0] is _EXPR_UNION:
            return "ExprSlot"
        return _union_member(args[0])
    return getattr(t, "__name__", repr(t))


if __name__ == "__main__":
    out = generate()
    if "--check" in sys.argv:
        existing = _TARGET.read_text()
        if existing != out:
            sys.stderr.write(
                "_generated.py is out of sync. Run: uv run python -m ontoloom.codegen.gen_patterns\n"
            )
            sys.exit(1)
    else:
        _TARGET.write_text(out)
        print(f"Wrote {_TARGET}")  # noqa: T201
