# Generated by ontoloom.codegen.gen_patterns. DO NOT EDIT.

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from ontoloom.ontology.models.literals import (
    DataRange,
    EntityType,
    FrozenModel,
    IRI,
    LangLiteral,
    TypedLiteral,
)
from ontoloom.ontology.patterns.slot import Slot

class Contains(FrozenModel):
    """Partial-set match: actual list must contain at least these items."""
    contains: tuple[ExprSlot, ...]

class NamedClassPattern(FrozenModel):
    type: Literal["NamedClassPattern"] = "NamedClassPattern"
    iri: Slot

class ObjectSomeValuesFromPattern(FrozenModel):
    type: Literal["ObjectSomeValuesFromPattern"] = "ObjectSomeValuesFromPattern"
    property: Slot
    filler: ExprSlot

class ObjectIntersectionOfPattern(FrozenModel):
    type: Literal["ObjectIntersectionOfPattern"] = "ObjectIntersectionOfPattern"
    operands: tuple[ExprSlot, ...] | Contains

class ObjectOneOfPattern(FrozenModel):
    type: Literal["ObjectOneOfPattern"] = "ObjectOneOfPattern"
    individual: Slot

class ObjectHasValuePattern(FrozenModel):
    type: Literal["ObjectHasValuePattern"] = "ObjectHasValuePattern"
    property: Slot
    individual: Slot

class ObjectHasSelfPattern(FrozenModel):
    type: Literal["ObjectHasSelfPattern"] = "ObjectHasSelfPattern"
    property: Slot

class DataSomeValuesFromPattern(FrozenModel):
    type: Literal["DataSomeValuesFromPattern"] = "DataSomeValuesFromPattern"
    property: Slot
    range: DataRange | Slot

class DataHasValuePattern(FrozenModel):
    type: Literal["DataHasValuePattern"] = "DataHasValuePattern"
    property: Slot
    value: TypedLiteral | LangLiteral | Slot

ExprSlot = Slot | NamedClassPattern | ObjectSomeValuesFromPattern | ObjectIntersectionOfPattern | ObjectOneOfPattern | ObjectHasValuePattern | ObjectHasSelfPattern | DataSomeValuesFromPattern | DataHasValuePattern

class AnnotationAssertionPattern(FrozenModel):
    type: Literal["AnnotationAssertionPattern"] = "AnnotationAssertionPattern"
    property: Slot
    subject: Slot
    value: IRI | TypedLiteral | LangLiteral | Slot

class SubClassOfPattern(FrozenModel):
    type: Literal["SubClassOfPattern"] = "SubClassOfPattern"
    sub_class: ExprSlot
    super_class: ExprSlot

class EquivalentClassesPattern(FrozenModel):
    type: Literal["EquivalentClassesPattern"] = "EquivalentClassesPattern"
    expressions: tuple[ExprSlot, ...] | Contains

class DisjointClassesPattern(FrozenModel):
    type: Literal["DisjointClassesPattern"] = "DisjointClassesPattern"
    expressions: tuple[ExprSlot, ...] | Contains

class SubObjectPropertyOfPattern(FrozenModel):
    type: Literal["SubObjectPropertyOfPattern"] = "SubObjectPropertyOfPattern"
    sub_property: Slot
    super_property: Slot

class SubObjectPropertyOfChainPattern(FrozenModel):
    type: Literal["SubObjectPropertyOfChainPattern"] = "SubObjectPropertyOfChainPattern"
    chain: tuple[Slot, ...]
    super_property: Slot

class EquivalentObjectPropertiesPattern(FrozenModel):
    type: Literal["EquivalentObjectPropertiesPattern"] = "EquivalentObjectPropertiesPattern"
    properties: tuple[Slot, ...] | Contains

class TransitiveObjectPropertyPattern(FrozenModel):
    type: Literal["TransitiveObjectPropertyPattern"] = "TransitiveObjectPropertyPattern"
    property: Slot

class ReflexiveObjectPropertyPattern(FrozenModel):
    type: Literal["ReflexiveObjectPropertyPattern"] = "ReflexiveObjectPropertyPattern"
    property: Slot

class ObjectPropertyDomainPattern(FrozenModel):
    type: Literal["ObjectPropertyDomainPattern"] = "ObjectPropertyDomainPattern"
    property: Slot
    domain: ExprSlot

class ObjectPropertyRangePattern(FrozenModel):
    type: Literal["ObjectPropertyRangePattern"] = "ObjectPropertyRangePattern"
    property: Slot
    range: ExprSlot

class SubDataPropertyOfPattern(FrozenModel):
    type: Literal["SubDataPropertyOfPattern"] = "SubDataPropertyOfPattern"
    sub_property: Slot
    super_property: Slot

class EquivalentDataPropertiesPattern(FrozenModel):
    type: Literal["EquivalentDataPropertiesPattern"] = "EquivalentDataPropertiesPattern"
    properties: tuple[Slot, ...] | Contains

class DataPropertyDomainPattern(FrozenModel):
    type: Literal["DataPropertyDomainPattern"] = "DataPropertyDomainPattern"
    property: Slot
    domain: ExprSlot

class DataPropertyRangePattern(FrozenModel):
    type: Literal["DataPropertyRangePattern"] = "DataPropertyRangePattern"
    property: Slot
    range: DataRange | Slot

class FunctionalDataPropertyPattern(FrozenModel):
    type: Literal["FunctionalDataPropertyPattern"] = "FunctionalDataPropertyPattern"
    property: Slot

class HasKeyPattern(FrozenModel):
    type: Literal["HasKeyPattern"] = "HasKeyPattern"
    class_expression: ExprSlot
    object_properties: tuple[Slot, ...] | Contains
    data_properties: tuple[Slot, ...] | Contains

class SubAnnotationPropertyOfPattern(FrozenModel):
    type: Literal["SubAnnotationPropertyOfPattern"] = "SubAnnotationPropertyOfPattern"
    sub_property: Slot
    super_property: Slot

class AnnotationPropertyDomainPattern(FrozenModel):
    type: Literal["AnnotationPropertyDomainPattern"] = "AnnotationPropertyDomainPattern"
    property: Slot
    domain: Slot

class AnnotationPropertyRangePattern(FrozenModel):
    type: Literal["AnnotationPropertyRangePattern"] = "AnnotationPropertyRangePattern"
    property: Slot
    range: Slot

class DatatypeDefinitionPattern(FrozenModel):
    type: Literal["DatatypeDefinitionPattern"] = "DatatypeDefinitionPattern"
    datatype: Slot
    data_range: DataRange | Slot

class DeclarationPattern(FrozenModel):
    type: Literal["DeclarationPattern"] = "DeclarationPattern"
    entity_type: EntityType | Slot
    iri: Slot

class ClassAssertionPattern(FrozenModel):
    type: Literal["ClassAssertionPattern"] = "ClassAssertionPattern"
    class_expression: ExprSlot
    individual: Slot

class ObjectPropertyAssertionPattern(FrozenModel):
    type: Literal["ObjectPropertyAssertionPattern"] = "ObjectPropertyAssertionPattern"
    property: Slot
    source: Slot
    target: Slot

class NegativeObjectPropertyAssertionPattern(FrozenModel):
    type: Literal["NegativeObjectPropertyAssertionPattern"] = "NegativeObjectPropertyAssertionPattern"
    property: Slot
    source: Slot
    target: Slot

class DataPropertyAssertionPattern(FrozenModel):
    type: Literal["DataPropertyAssertionPattern"] = "DataPropertyAssertionPattern"
    property: Slot
    individual: Slot
    value: TypedLiteral | LangLiteral | Slot

class NegativeDataPropertyAssertionPattern(FrozenModel):
    type: Literal["NegativeDataPropertyAssertionPattern"] = "NegativeDataPropertyAssertionPattern"
    property: Slot
    individual: Slot
    value: TypedLiteral | LangLiteral | Slot

class SameIndividualPattern(FrozenModel):
    type: Literal["SameIndividualPattern"] = "SameIndividualPattern"
    individuals: tuple[Slot, ...] | Contains

class DifferentIndividualsPattern(FrozenModel):
    type: Literal["DifferentIndividualsPattern"] = "DifferentIndividualsPattern"
    individuals: tuple[Slot, ...] | Contains

ExpressionPattern = NamedClassPattern | ObjectSomeValuesFromPattern | ObjectIntersectionOfPattern | ObjectOneOfPattern | ObjectHasValuePattern | ObjectHasSelfPattern | DataSomeValuesFromPattern | DataHasValuePattern
AxiomPattern = AnnotationAssertionPattern | SubClassOfPattern | EquivalentClassesPattern | DisjointClassesPattern | SubObjectPropertyOfPattern | SubObjectPropertyOfChainPattern | EquivalentObjectPropertiesPattern | TransitiveObjectPropertyPattern | ReflexiveObjectPropertyPattern | ObjectPropertyDomainPattern | ObjectPropertyRangePattern | SubDataPropertyOfPattern | EquivalentDataPropertiesPattern | DataPropertyDomainPattern | DataPropertyRangePattern | FunctionalDataPropertyPattern | HasKeyPattern | SubAnnotationPropertyOfPattern | AnnotationPropertyDomainPattern | AnnotationPropertyRangePattern | DatatypeDefinitionPattern | DeclarationPattern | ClassAssertionPattern | ObjectPropertyAssertionPattern | NegativeObjectPropertyAssertionPattern | DataPropertyAssertionPattern | NegativeDataPropertyAssertionPattern | SameIndividualPattern | DifferentIndividualsPattern
Pattern = Annotated[ExpressionPattern | AxiomPattern, Field(discriminator="type")]

Contains.model_rebuild()
ObjectSomeValuesFromPattern.model_rebuild()
ObjectIntersectionOfPattern.model_rebuild()
SubClassOfPattern.model_rebuild()
EquivalentClassesPattern.model_rebuild()
DisjointClassesPattern.model_rebuild()
EquivalentObjectPropertiesPattern.model_rebuild()
ObjectPropertyDomainPattern.model_rebuild()
ObjectPropertyRangePattern.model_rebuild()
EquivalentDataPropertiesPattern.model_rebuild()
DataPropertyDomainPattern.model_rebuild()
HasKeyPattern.model_rebuild()
ClassAssertionPattern.model_rebuild()
SameIndividualPattern.model_rebuild()
DifferentIndividualsPattern.model_rebuild()
