from ontoloom.codegen.gen_patterns import generate


def test_gen_patterns_produces_python_source():
    source = generate()
    assert source.startswith("# Generated by ontoloom.codegen.gen_patterns. DO NOT EDIT.")
    assert "class SubClassOfPattern" in source
    assert "class NamedClassPattern" in source
    assert "class ContainsExpr" in source
    assert "class ContainsSlot" in source
    assert "Pattern = Annotated[" in source
    assert 'discriminator="type"' in source


def test_gen_patterns_is_deterministic():
    assert generate() == generate()


def test_gen_patterns_iri_fields_become_slot():
    source = generate()
    # AnnotationAssertion.property (IRI) → Slot
    assert "property: Slot" in source


def test_gen_patterns_class_expression_becomes_exprslot():
    source = generate()
    # SubClassOf.sub_class (ClassExpression) → ExprSlot
    assert "sub_class: ExprSlot" in source
    assert "super_class: ExprSlot" in source


def test_gen_patterns_unordered_tuple_gets_contains():
    source = generate()
    assert "tuple[ExprSlot, ...] | ContainsExpr" in source
    assert "tuple[Slot, ...] | ContainsSlot" in source


def test_gen_patterns_ordered_tuple_has_no_contains():
    source = generate()
    # SubObjectPropertyOfChain.chain is ordered — no Contains
    assert "chain: tuple[Slot, ...]" in source


def test_gen_patterns_data_range_gets_slot_option():
    source = generate()
    assert "DataRange | Slot" in source


def test_gen_patterns_exprslot_alias_defined():
    source = generate()
    assert "ExprSlot = Slot |" in source


def test_new_axiom_type_works_without_module_edits():
    """Adding a new axiom type with markers — canonical and extract pick it up
    purely from the field metadata, no edits to canonical.py or extract.py needed."""
    from typing import Annotated, Literal

    from ontoloom.ontology.canonical import canonical_json
    from ontoloom.ontology.extract import iter_axiom_entities
    from ontoloom.ontology.models.base import BaseAxiom
    from ontoloom.ontology.models.literals import IRI, EntityType, Position
    from ontoloom.ontology.models.markers import EntityKind, EntityPosition, Unordered
    from pydantic import Field

    class _TestAxiom(BaseAxiom):
        type: Literal["_TestAxiom"] = "_TestAxiom"
        members: Annotated[
            tuple[IRI, ...],
            Unordered(),
            EntityKind(EntityType.CLASS),
            EntityPosition(Position.MEMBER),
            Field(min_length=2),
        ]

    a = _TestAxiom(members=(IRI("ex:Dog"), IRI("ex:Cat")))
    b = _TestAxiom(members=(IRI("ex:Cat"), IRI("ex:Dog")))
    assert canonical_json(a) == canonical_json(b)  # Unordered marker → sorted

    entities = set(iter_axiom_entities(a))
    assert (IRI("ex:Dog"), EntityType.CLASS, Position.MEMBER) in entities
    assert (IRI("ex:Cat"), EntityType.CLASS, Position.MEMBER) in entities


# -- P-03-10: Cross-process determinism --


def test_gen_patterns_cross_process_deterministic():
    import subprocess
    import sys

    script = "from ontoloom.codegen.gen_patterns import generate; print(generate(), end='')"

    def run(seed: int):
        return subprocess.run(
            [sys.executable, "-c", script],
            capture_output=True,
            text=True,
            env={**__import__("os").environ, "PYTHONHASHSEED": str(seed)},
            check=True,
        ).stdout

    assert run(0) == run(1)


# -- P-03-12: Structural codegen tests --


def test_gen_patterns_fields_match_axiom_fields():
    from typing import get_args

    from ontoloom.ontology.models.axioms import Axiom
    from ontoloom.ontology.patterns._generated import AxiomPattern

    skip = frozenset(("type", "annotations"))
    axiom_classes = {cls.__name__: cls for cls in get_args(get_args(Axiom)[0])}
    pattern_classes = {cls.__name__: cls for cls in get_args(AxiomPattern)}

    for pattern_name, pattern_cls in pattern_classes.items():
        axiom_name = pattern_name.removesuffix("Pattern")
        axiom_cls = axiom_classes.get(axiom_name)
        if axiom_cls is None:
            continue

        axiom_fields = set(axiom_cls.model_fields) - skip
        pattern_fields = set(pattern_cls.model_fields) - skip
        assert pattern_fields == axiom_fields, (
            f"{pattern_name}: expected fields {axiom_fields}, got {pattern_fields}"
        )


def test_exprslot_and_axiomslot_exact_membership():
    from typing import get_args

    from ontoloom.ontology.patterns._generated import AxiomPattern, ExpressionPattern, ExprSlot
    from ontoloom.ontology.patterns.slot import Slot

    expr_types = set(get_args(ExpressionPattern))
    exprslot_types = set(get_args(ExprSlot))
    assert Slot in exprslot_types
    assert exprslot_types == {Slot} | expr_types

    # AxiomPattern is a plain union of all axiom pattern classes
    axiom_types = set(get_args(AxiomPattern))
    assert len(axiom_types) > 0


def test_expression_container_types_reflective_derivation():
    """_EXPRESSION_CONTAINER_TYPES must match the axiom types that actually carry ClassExpression fields."""
    from ontoloom.ontology.patterns.search import _EXPRESSION_CONTAINER_TYPES

    expected = frozenset(
        {
            "ClassAssertion",
            "DataPropertyDomain",
            "DisjointClasses",
            "EquivalentClasses",
            "HasKey",
            "ObjectPropertyDomain",
            "ObjectPropertyRange",
            "SubClassOf",
        }
    )
    assert expected == _EXPRESSION_CONTAINER_TYPES


def test_gen_patterns_field_type_transformations():
    """Key field-type transformations verified at runtime via model_fields annotations."""
    from ontoloom.ontology.patterns import _generated as gen
    from ontoloom.ontology.patterns.slot import Slot

    # IRI field → Slot
    ann = gen.AnnotationAssertionPattern.model_fields["property"].annotation
    assert ann is Slot, f"expected Slot for .property, got {ann}"

    # ClassExpression field → ExprSlot (a union containing Slot)
    ann = gen.SubClassOfPattern.model_fields["sub_class"].annotation
    assert hasattr(ann, "__args__"), f"expected union for .sub_class, got {ann}"
    assert Slot in ann.__args__, f"Slot missing from ExprSlot union: {ann}"

    # DataRange field → DataRange | Slot (union containing Slot)
    ann = gen.DataPropertyRangePattern.model_fields["range"].annotation
    assert hasattr(ann, "__args__"), f"expected union for .range, got {ann}"
    assert Slot in ann.__args__, f"Slot missing from DataRange|Slot union: {ann}"

    # Ordered tuple of IRI → tuple[Slot, ...] (no Contains)
    ann = gen.SubObjectPropertyOfChainPattern.model_fields["chain"].annotation
    assert ann == tuple[Slot, ...], f"expected tuple[Slot, ...] for .chain, got {ann}"

    # Unordered tuple of IRI → tuple[Slot, ...] | ContainsSlot
    ann = gen.EquivalentObjectPropertiesPattern.model_fields["properties"].annotation
    assert hasattr(ann, "__args__"), f"expected union for .properties, got {ann}"
    assert gen.ContainsSlot in ann.__args__
