from ontoloom.codegen.gen_patterns import generate


def test_gen_patterns_produces_python_source():
    source = generate()
    assert source.startswith("# Generated by ontoloom.codegen.gen_patterns. DO NOT EDIT.")
    assert "class SubClassOfPattern" in source
    assert "class NamedClassPattern" in source
    assert "class Contains" in source
    assert "Pattern = Annotated[" in source
    assert 'discriminator="type"' in source


def test_gen_patterns_is_deterministic():
    assert generate() == generate()


def test_gen_patterns_iri_fields_become_slot():
    source = generate()
    # AnnotationAssertion.property (IRI) → Slot
    assert "property: Slot" in source


def test_gen_patterns_class_expression_becomes_exprslot():
    source = generate()
    # SubClassOf.sub_class (ClassExpression) → ExprSlot
    assert "sub_class: ExprSlot" in source
    assert "super_class: ExprSlot" in source


def test_gen_patterns_unordered_tuple_gets_contains():
    source = generate()
    assert "tuple[ExprSlot, ...] | Contains" in source
    assert "tuple[Slot, ...] | Contains" in source


def test_gen_patterns_ordered_tuple_has_no_contains():
    source = generate()
    # SubObjectPropertyOfChain.chain is ordered — no Contains
    assert "chain: tuple[Slot, ...]" in source


def test_gen_patterns_data_range_gets_slot_option():
    source = generate()
    assert "DataRange | Slot" in source


def test_gen_patterns_exprslot_alias_defined():
    source = generate()
    assert "ExprSlot = Slot |" in source


def test_new_axiom_type_works_without_module_edits():
    """Adding a new axiom type with markers — canonical and extract pick it up
    purely from the field metadata, no edits to canonical.py or extract.py needed."""
    from typing import Annotated, Literal

    from ontoloom.ontology.canonical import canonical_json
    from ontoloom.ontology.extract import iter_axiom_entities
    from ontoloom.ontology.models.literals import IRI, EntityType, FrozenModel, Position
    from ontoloom.ontology.models.markers import EntityKind, EntityPosition, Unordered
    from pydantic import Field

    class _TestAxiom(FrozenModel):
        type: Literal["_TestAxiom"] = "_TestAxiom"
        members: Annotated[
            tuple[IRI, ...],
            Unordered(),
            EntityKind(EntityType.CLASS),
            EntityPosition(Position.MEMBER),
            Field(min_length=2),
        ]

    a = _TestAxiom(members=(IRI("ex:Dog"), IRI("ex:Cat")))
    b = _TestAxiom(members=(IRI("ex:Cat"), IRI("ex:Dog")))
    assert canonical_json(a) == canonical_json(b)  # Unordered marker → sorted

    entities = set(iter_axiom_entities(a))  # pyright: ignore[reportArgumentType]
    assert (IRI("ex:Dog"), EntityType.CLASS, Position.MEMBER) in entities
    assert (IRI("ex:Cat"), EntityType.CLASS, Position.MEMBER) in entities
